"""Frozen initial schema; supports adoption of existing installations."""
from alembic import op
revision = '0000_legacy_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute('\nCREATE TABLE IF NOT EXISTS audit_events (\n\tid VARCHAR(36) NOT NULL, \n\ttenant_id VARCHAR(80) NOT NULL, \n\tactor_id VARCHAR(36) NOT NULL, \n\taction VARCHAR(120) NOT NULL, \n\tresource_type VARCHAR(80) NOT NULL, \n\tresource_id VARCHAR(160) NOT NULL, \n\toutcome VARCHAR(24) NOT NULL, \n\tmetadata_json JSON NOT NULL, \n\toccurred_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_audit_events_tenant_id ON audit_events (tenant_id)')
    op.execute('\nCREATE TABLE IF NOT EXISTS behavior_telemetry (\n\ttenant_id VARCHAR(80) NOT NULL, \n\tid VARCHAR(80) NOT NULL, \n\tentity VARCHAR(160) NOT NULL, \n\tmetric VARCHAR(80) NOT NULL, \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tpayload JSON NOT NULL, \n\tPRIMARY KEY (tenant_id, id)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_behavior_telemetry_entity ON behavior_telemetry (entity)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_behavior_telemetry_observed_at ON behavior_telemetry (observed_at)')
    op.execute('\nCREATE TABLE IF NOT EXISTS conversation_messages (\n\tid VARCHAR(36) NOT NULL, \n\ttenant_id VARCHAR(80) NOT NULL, \n\tuser_id VARCHAR(36) NOT NULL, \n\tconversation_id VARCHAR(36) NOT NULL, \n\trole VARCHAR(16) NOT NULL, \n\tcontent TEXT NOT NULL, \n\tprovider VARCHAR(40), \n\tmodel VARCHAR(160), \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_conversation_messages_tenant_id ON conversation_messages (tenant_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_conversation_messages_user_id ON conversation_messages (user_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_conversation_messages_conversation_id ON conversation_messages (conversation_id)')
    op.execute('\nCREATE TABLE IF NOT EXISTS copilot_records (\n\ttenant_id VARCHAR(80) NOT NULL, \n\tuser_id VARCHAR(36) NOT NULL, \n\tkind VARCHAR(32) NOT NULL, \n\tid VARCHAR(80) NOT NULL, \n\tpayload JSON NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (tenant_id, user_id, kind, id)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_copilot_records_updated_at ON copilot_records (updated_at)')
    op.execute('\nCREATE TABLE IF NOT EXISTS entity_observations (\n\ttenant_id VARCHAR(80) NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tentity_id VARCHAR(64) NOT NULL, \n\tdocument_id VARCHAR(36) NOT NULL, \n\tsource_id VARCHAR(36) NOT NULL, \n\tconfidence INTEGER NOT NULL, \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (tenant_id, id), \n\tCONSTRAINT uq_entity_observation_document UNIQUE (tenant_id, entity_id, document_id)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_entity_observations_source_id ON entity_observations (source_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_entity_observations_document_id ON entity_observations (document_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_entity_observations_entity_id ON entity_observations (entity_id)')
    op.execute('\nCREATE TABLE IF NOT EXISTS intelligence_entities (\n\ttenant_id VARCHAR(80) NOT NULL, \n\tid VARCHAR(64) NOT NULL, \n\tentity_type VARCHAR(32) NOT NULL, \n\tvalue VARCHAR(2048) NOT NULL, \n\tconfidence INTEGER NOT NULL, \n\textraction_method VARCHAR(32) NOT NULL, \n\tfirst_seen TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_seen TIMESTAMP WITH TIME ZONE NOT NULL, \n\tstatus VARCHAR(16) NOT NULL, \n\tmetadata_json JSON NOT NULL, \n\tPRIMARY KEY (tenant_id, id), \n\tCONSTRAINT uq_entity_tenant_type_value UNIQUE (tenant_id, entity_type, value)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_intelligence_entities_entity_type ON intelligence_entities (entity_type)')
    op.execute('\nCREATE TABLE IF NOT EXISTS intelligence_sources (\n\ttenant_id VARCHAR(80) NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tname VARCHAR(160) NOT NULL, \n\turl VARCHAR(2048) NOT NULL, \n\tcanonical_url VARCHAR(2048) NOT NULL, \n\tsource_type VARCHAR(32) NOT NULL, \n\tcategory VARCHAR(64) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\thealth VARCHAR(16) NOT NULL, \n\tcrawl_policy VARCHAR(16) NOT NULL, \n\tfrequency_minutes INTEGER NOT NULL, \n\tpriority INTEGER NOT NULL, \n\ttrust_level VARCHAR(16) NOT NULL, \n\tparser_type VARCHAR(16) NOT NULL, \n\trobots_status VARCHAR(16) NOT NULL, \n\tlast_checked_at TIMESTAMP WITH TIME ZONE, \n\tlast_crawled_at TIMESTAMP WITH TIME ZONE, \n\tlast_success_at TIMESTAMP WITH TIME ZONE, \n\tlast_failed_at TIMESTAMP WITH TIME ZONE, \n\tnext_scheduled_at TIMESTAMP WITH TIME ZONE, \n\tfailure_count INTEGER NOT NULL, \n\tlast_error TEXT, \n\ttags JSON NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (tenant_id, id), \n\tCONSTRAINT uq_source_tenant_canonical_url UNIQUE (tenant_id, canonical_url)\n)\n\n')
    op.execute('\nCREATE TABLE IF NOT EXISTS keyword_monitors (\n\tid VARCHAR(36) NOT NULL, \n\ttenant_id VARCHAR(80) NOT NULL, \n\tterm VARCHAR(256) NOT NULL, \n\tcategories JSON NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tcreated_by VARCHAR(36) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_keyword_monitors_tenant_term UNIQUE (tenant_id, term)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_keyword_monitors_tenant_id ON keyword_monitors (tenant_id)')
    op.execute('\nCREATE TABLE IF NOT EXISTS operational_alerts (\n\tid VARCHAR(36) NOT NULL, \n\ttenant_id VARCHAR(80) NOT NULL, \n\tdedupe_key VARCHAR(240) NOT NULL, \n\ttitle VARCHAR(512) NOT NULL, \n\tseverity VARCHAR(16) NOT NULL, \n\tscore INTEGER NOT NULL, \n\tstatus VARCHAR(24) NOT NULL, \n\tevidence JSON NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_operational_alert_tenant_key UNIQUE (tenant_id, dedupe_key)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_operational_alerts_tenant_id ON operational_alerts (tenant_id)')
    op.execute('\nCREATE TABLE IF NOT EXISTS report_schedules (\n\ttenant_id VARCHAR(80) NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tname VARCHAR(80) NOT NULL, \n\tcron VARCHAR(100) NOT NULL, \n\tformat VARCHAR(8) NOT NULL, \n\trecipients JSON NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tdelivery_status VARCHAR(32) NOT NULL, \n\tlast_run_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (tenant_id, id), \n\tCONSTRAINT uq_report_schedule_tenant_name UNIQUE (tenant_id, name)\n)\n\n')
    op.execute('\nCREATE TABLE IF NOT EXISTS revoked_tokens (\n\tdigest VARCHAR(64) NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (digest)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_revoked_tokens_expires_at ON revoked_tokens (expires_at)')
    op.execute('\nCREATE TABLE IF NOT EXISTS source_crawl_jobs (\n\ttenant_id VARCHAR(80) NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tsource_id VARCHAR(36) NOT NULL, \n\tstatus VARCHAR(16) NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tpages_requested INTEGER NOT NULL, \n\tpages_successful INTEGER NOT NULL, \n\tpages_failed INTEGER NOT NULL, \n\tbytes_downloaded INTEGER NOT NULL, \n\trecords_extracted INTEGER NOT NULL, \n\tduplicates_found INTEGER NOT NULL, \n\terror TEXT, \n\tPRIMARY KEY (tenant_id, id)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_source_crawl_jobs_source_id ON source_crawl_jobs (source_id)')
    op.execute('\nCREATE TABLE IF NOT EXISTS source_documents (\n\ttenant_id VARCHAR(80) NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tsource_id VARCHAR(36) NOT NULL, \n\tcrawl_id VARCHAR(36) NOT NULL, \n\tsource_url VARCHAR(2048) NOT NULL, \n\tcanonical_url VARCHAR(2048) NOT NULL, \n\ttitle VARCHAR(512) NOT NULL, \n\traw_content TEXT NOT NULL, \n\tnormalized_text TEXT NOT NULL, \n\tcontent_hash VARCHAR(64) NOT NULL, \n\tcollected_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tpublished_at TIMESTAMP WITH TIME ZONE, \n\tfirst_seen TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_seen TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsource_category VARCHAR(64) NOT NULL, \n\tlanguage VARCHAR(16) NOT NULL, \n\tstatus VARCHAR(16) NOT NULL, \n\tmetadata_json JSON NOT NULL, \n\ttags JSON NOT NULL, \n\tPRIMARY KEY (tenant_id, id), \n\tCONSTRAINT uq_source_document_tenant_hash UNIQUE (tenant_id, content_hash)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_source_documents_crawl_id ON source_documents (crawl_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_source_documents_source_id ON source_documents (source_id)')
    op.execute('\nCREATE TABLE IF NOT EXISTS tenant_extensions (\n\ttenant_id VARCHAR(80) NOT NULL, \n\tid VARCHAR(80) NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tinstalled_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (tenant_id, id)\n)\n\n')
    op.execute('\nCREATE TABLE IF NOT EXISTS tenant_intelligence (\n\ttenant_id VARCHAR(80) NOT NULL, \n\tcollection VARCHAR(40) NOT NULL, \n\tid VARCHAR(80) NOT NULL, \n\tpayload JSON NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (tenant_id, collection, id)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_tenant_intelligence_updated_at ON tenant_intelligence (updated_at)')
    op.execute('\nCREATE TABLE IF NOT EXISTS tenants (\n\tid VARCHAR(80) NOT NULL, \n\tname VARCHAR(160) NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n')
    op.execute('\nCREATE TABLE IF NOT EXISTS threat_events (\n\tid VARCHAR(36) NOT NULL, \n\ttenant_id VARCHAR(80) NOT NULL, \n\tevent_type VARCHAR(64) NOT NULL, \n\tdedupe_key VARCHAR(240) NOT NULL, \n\tsource_id VARCHAR(36) NOT NULL, \n\tdocument_id VARCHAR(36) NOT NULL, \n\tentity_id VARCHAR(64), \n\tseverity VARCHAR(16) NOT NULL, \n\tconfidence INTEGER NOT NULL, \n\treason TEXT NOT NULL, \n\tevidence JSON NOT NULL, \n\tstatus VARCHAR(24) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_threat_event_tenant_key UNIQUE (tenant_id, dedupe_key)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_threat_events_tenant_id ON threat_events (tenant_id)')
    op.execute('\nCREATE TABLE IF NOT EXISTS threat_feed_items (\n\tid VARCHAR(36) NOT NULL, \n\tsource VARCHAR(80) NOT NULL, \n\texternal_id VARCHAR(160) NOT NULL, \n\ttitle VARCHAR(512) NOT NULL, \n\tsummary TEXT NOT NULL, \n\tseverity VARCHAR(16) NOT NULL, \n\tpublished_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\traw JSON NOT NULL, \n\tingested_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_threat_feed_source_external UNIQUE (source, external_id)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_threat_feed_items_source ON threat_feed_items (source)')
    op.execute('\nCREATE TABLE IF NOT EXISTS users (\n\tid VARCHAR(36) NOT NULL, \n\ttenant_id VARCHAR(80) NOT NULL, \n\temail VARCHAR(320) NOT NULL, \n\tdisplay_name VARCHAR(120) NOT NULL, \n\tpassword_hash VARCHAR(256) NOT NULL, \n\trole VARCHAR(20) NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_users_tenant_email UNIQUE (tenant_id, email)\n)\n\n')
    op.execute('CREATE INDEX IF NOT EXISTS ix_users_tenant_id ON users (tenant_id)')
    op.execute('\nCREATE TABLE IF NOT EXISTS webhook_subscriptions (\n\ttenant_id VARCHAR(80) NOT NULL, \n\tid VARCHAR(36) NOT NULL, \n\tname VARCHAR(80) NOT NULL, \n\turl VARCHAR(2048) NOT NULL, \n\tevent_types JSON NOT NULL, \n\tminimum_severity VARCHAR(16) NOT NULL, \n\tencrypted_secret TEXT NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tfailure_count INTEGER NOT NULL, \n\tlast_delivered_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (tenant_id, id), \n\tCONSTRAINT uq_webhook_tenant_name UNIQUE (tenant_id, name)\n)\n\n')


def downgrade():
    raise RuntimeError('Baseline downgrade is destructive; restore a verified backup instead')
