"use client";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeHighlight from "rehype-highlight";
import { Bot, X, Maximize2, Minimize2, Plus, Send, Square, Copy, RefreshCw, ShieldCheck, Bell, Settings2, Search, ArrowUpRight } from "lucide-react";
import { apiRequest, apiFetch } from "../lib/api";

type Source = { source: string; reference?: string; retrieved_at?: string; mode?: string };
type Message = { role: "user" | "assistant"; content: string; sources?: Source[]; provider?: string; model?: string };
type Session = { id: string; title: string; updated_at: string };
type Notice = { id: string; title: string; severity: string; state: string; group: string; alert_id?: string; snoozed_until?: string };
type Config = { provider: "local" | "external"; model: string; endpoint: string; enabled?: boolean; api_key?: string; temperature: number; context_window: number; max_tokens: number; timeout: number; secret_env: string; has_key?: boolean };
type Preferences = { memory_enabled: boolean; preference: string; muted_groups: string[] };
type Status = { services: Record<string,string>; local_model: { state: string; model: string; backend?: string; detail?: string }; knowledge: { mode: string; chunks: number; sources: string[]; indexed_at: string }; models: Record<string,Config>; usage: { latency_ms: number; tokens: number|null; provider: string; at: string }[]; tool_calls: { id: string; tool: string; at: string; mode: string }[]; sources: Record<string,string> };
const providers = ["local","external"];
const defaults: Config = {provider:"local",model:"selected",endpoint:"",temperature:0.2,context_window:4096,max_tokens:512,timeout:180,secret_env:""};

export function askCopilot(alertId: string) { window.dispatchEvent(new CustomEvent("darktrace:ask-ai", {detail:{alertId}})); }

export function Copilot({apiBase,role,commandCenter=false}:{apiBase:string;role:string;commandCenter?:boolean}) {
  const [open,setOpen]=useState(commandCenter), [expanded,setExpanded]=useState(commandCenter);
  const [view,setView]=useState("chat"),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState("");
  const [sessions,setSessions]=useState<Session[]>([]),[search,setSearch]=useState(""),[sessionId,setSessionId]=useState<string>();
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[activity,setActivity]=useState("Private analysis · read-only tools");
  const [status,setStatus]=useState<Status>(),[notices,setNotices]=useState<Notice[]>([]),[toast,setToast]=useState<Notice>();
  const [preferences,setPreferences]=useState<Preferences>({memory_enabled:true,preference:"",muted_groups:[]});
  const [slot,setSlot]=useState("primary"),[modelForm,setModelForm]=useState<Config>(defaults);
  const cloud=false; const setCloud=(_: boolean)=>undefined;
  const abort=useRef<AbortController|null>(null),scroll=useRef<HTMLDivElement>(null),follow=useRef(true),seen=useRef(new Set<string>());
  const request=useCallback(<T,>(path:string,init?:RequestInit)=>apiRequest<T>(apiBase,"/copilot"+path,init),[apiBase]);
  const refresh=useCallback(async()=>{try{setStatus(await request<Status>("/status"));}catch(e){setError(e instanceof Error?e.message:"Copilot unavailable");}},[request]);
  const history=useCallback(async()=>{setSessions(await request<Session[]>("/sessions?q="+encodeURIComponent(search)));},[request,search]);
  useEffect(()=>{void refresh();void request<Preferences>("/preferences").then(setPreferences).catch(()=>{});const timer=setInterval(refresh,60000);return()=>clearInterval(timer);},[refresh,request]);
  useEffect(()=>{const timer=setTimeout(()=>void history().catch(()=>{}),250);return()=>clearTimeout(timer);},[history]);
  useEffect(()=>{if(status?.models[slot])setModelForm(status.models[slot]);},[slot,status]);
  useEffect(()=>{let mounted=true;async function poll(){try{const rows=await request<Notice[]>("/notifications");if(!mounted)return;setNotices(rows);const n=rows.find(n=>(n.state==="new"||(n.state==="snooze"&&new Date(n.snoozed_until??0).getTime()<Date.now()))&&!seen.current.has(n.id+(n.snoozed_until??"")));if(n){seen.current.add(n.id+(n.snoozed_until??""));setToast(n);await request("/notifications/"+n.id,{method:"POST",body:JSON.stringify({action:"seen"})});}}catch{/* Existing workspace remains usable during outages. */}}void poll();const timer=setInterval(poll,30000);return()=>{mounted=false;clearInterval(timer)};},[request]);
  useEffect(()=>{if(follow.current&&scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;},[messages,activity]);
  useEffect(()=>()=>abort.current?.abort(),[]);

  const send=useCallback(async(question:string,regenerate=false,alertId?:string)=>{
    if(busy||!question.trim())return;
    setOpen(true);setView("chat");setBusy(true);setError("");setInput("");follow.current=true;
    const existing=regenerate?messages.slice(0,-2):messages;
    setMessages([...existing,{role:"user",content:question},{role:"assistant",content:""}]);
    const controller=new AbortController();abort.current=controller;
    let text="";
    try{
      const response=await apiFetch(apiBase+"/api/v1/copilot/chat",{method:"POST",headers:{"Content-Type":"application/json"},signal:controller.signal,body:JSON.stringify({message:question,conversation_id:sessionId,regenerate,alert_id:alertId,slot:"primary"})});
      if(!response.ok){if(response.status===401)window.dispatchEvent(new Event("darktracex:expired"));const data=await response.json();throw new Error(typeof data.detail==="string"?data.detail:"Unable to start generation");}
      if(!response.body)throw new Error("Streaming is unavailable");
      const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="",done=false;
      while(!done){const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});const frames=buffer.split("\n\n");buffer=frames.pop()??"";
        for(const frame of frames){if(!frame.startsWith("data: "))continue;const event=JSON.parse(frame.slice(6));
          if(event.type==="provider")setActivity(`${event.provider} · ${event.model}${event.fallback?" · fallback":""}`);
          if(event.type==="tool")setActivity(`Reading ${event.tool} · ${event.mode}`);
          if(event.type==="delta"){text+=event.text;setMessages([...existing,{role:"user",content:question},{role:"assistant",content:text}]);}
          if(event.type==="notice"||event.type==="fallback")setActivity(event.message??event.reason);
          if(event.type==="error")throw new Error(event.message);
          if(event.type==="done"){done=true;if(preferences.memory_enabled)setSessionId(event.id);setMessages([...existing,{role:"user",content:question},{role:"assistant",content:text,sources:event.sources,provider:event.stats.provider,model:event.stats.model}]);setActivity(`${event.stats.provider} · ${(event.stats.latency_ms/1000).toFixed(1)}s · ${event.stats.tokens??"—"} tokens`);}
        }
      }
      if(!done)throw new Error("Stream ended before completion. Partial text was not saved.");
      await history();void refresh();
    }catch(e){setMessages(messages);setError(e instanceof Error&&e.name==="AbortError"?"Generation stopped. Partial response was not saved.":e instanceof Error?e.message:"Generation failed");}
    finally{setBusy(false);abort.current=null;}
  },[apiBase,busy,history,messages,preferences.memory_enabled,refresh,sessionId]);

  useEffect(()=>{function ask(event:Event){const id=(event as CustomEvent<{alertId:string}>).detail.alertId;void send("Explain this alert: observed facts, impact, confidence and defensive investigation steps.",false,id);}function settings(){setOpen(true);setView(role==="admin"?"models":"system");}window.addEventListener("darktrace:ask-ai",ask);window.addEventListener("darktrace:ai-settings",settings);return()=>{window.removeEventListener("darktrace:ask-ai",ask);window.removeEventListener("darktrace:ai-settings",settings);};},[send,role]);
  async function loadSession(id:string){if(busy)return;try{const data=await request<{messages:Message[]}>("/sessions/"+id);setSessionId(id);setMessages(data.messages);setError("");}catch(e){setError(String(e));}}
  async function clear(){if(!sessionId){setMessages([]);return;}if(!window.confirm("Delete this conversation and its incident context?"))return;await request("/sessions/"+sessionId,{method:"DELETE"});setSessionId(undefined);setMessages([]);await history();}
  async function action(n:Notice,action:string){if(action==="resolve"&&!window.confirm("Mark the underlying alert resolved?"))return;try{await request("/notifications/"+n.id,{method:"POST",body:JSON.stringify({action,confirmed:action==="resolve"})});setNotices(rows=>rows.map(row=>row.id===n.id?{...row,state:action}:row));setToast(undefined);}catch(e){setError(String(e));}}
  async function saveModel(e:FormEvent){e.preventDefault();try{const {has_key,...body}=modelForm;void has_key;await request("/models/"+slot,{method:"PUT",body:JSON.stringify(body)});setError("");setActivity("AI settings saved");await refresh();}catch(e){setError(String(e));}}
  async function testExternal(){try{await request("/models/test",{method:"POST"});setError("");setActivity("External connection verified");}catch(e){setError(String(e));}}
  async function saveMemory(next:Preferences){try{setPreferences(await request<Preferences>("/preferences",{method:"PUT",body:JSON.stringify(next)}));if(!next.memory_enabled)setSessionId(undefined);}catch(e){setError(String(e));}}
  const modelState=status?.local_model.state??"OFFLINE";
  return <>
    {toast&&!open&&<aside className="copilot-toast" role="status"><ShieldCheck size={18}/><div><small>{toast.severity} · VERIFIED EVENT</small><p>{toast.title}</p><button onClick={()=>{setOpen(true);setView("signals");setToast(undefined);}}>Open alert</button>{toast.alert_id&&<button onClick={()=>{void send("Explain this alert and recommended defensive next steps.",false,toast.alert_id);setToast(undefined);}}>Ask AI</button>}<button onClick={()=>void action(toast,"dismiss")}>Dismiss</button></div></aside>}
    {!open&&<button className="copilot-launcher" aria-label="Open DarkTrace AI copilot" onClick={()=>setOpen(true)}><Bot size={25}/><span><strong>DARKTRACE AI</strong><small><i className={modelState.toLowerCase()}/>{modelState}</small></span></button>}
    {open&&<section aria-label="DarkTrace cybersecurity copilot" className={`copilot-panel ${expanded?"expanded":""}`}>
      <header className="copilot-header"><div className="copilot-emblem"><Bot size={24}/></div><div><strong>DARKTRACE <em>COPILOT</em></strong><small><i className={modelState.toLowerCase()}/>{modelState} · {status?.local_model.model??"Model unavailable"}</small></div><button title="New conversation" aria-label="New conversation" disabled={busy} onClick={()=>{setSessionId(undefined);setMessages([]);setView("chat");setError("");}}><Plus size={18}/></button><a title="AI Command Center" aria-label="AI Command Center" href="/ai-command-center"><ArrowUpRight size={18}/></a><button aria-label={expanded?"Restore panel":"Maximize copilot"} onClick={()=>setExpanded(!expanded)}>{expanded?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</button><button aria-label="Minimize copilot" onClick={()=>setOpen(false)}><X size={18}/></button></header>
      <nav className="copilot-tabs">{["chat","signals","system",...(role==="admin"?["models"]:[])].map(v=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}>{v==="models"?"AI Models":v==="signals"?"AI Alerts":v==="system"?"Command Center":"Investigation"}</button>)}</nav>
      {error&&<div className="copilot-error" role="alert">{error}</div>}
      {view==="chat"&&<div className="copilot-chat-layout"><aside className="copilot-history"><label><Search size={14}/><input aria-label="Search chat history" placeholder="Search investigations" value={search} onChange={e=>setSearch(e.target.value)}/></label>{sessions.map(s=><button disabled={busy} className={s.id===sessionId?"selected":""} key={s.id} onClick={()=>void loadSession(s.id)}>{s.title}<small>{new Date(s.updated_at).toLocaleDateString()}</small></button>)}{!sessions.length&&<p>No saved investigations</p>}</aside><div className="copilot-chat"><div className="copilot-messages" ref={scroll} onScroll={e=>{const el=e.currentTarget;follow.current=el.scrollHeight-el.scrollTop-el.clientHeight<80;}} aria-live="polite">
        {!messages.length&&<div className="copilot-welcome"><ShieldCheck size={42}/><p>YOUR PRIVATE SOC PARTNER</p><h2>Evidence first.<br/>Clarity follows.</h2><span>Investigate alerts, inspect service health and understand your threat intelligence.</span>{["Which services are unhealthy?","Show critical alerts.","Summarize today's threats.","Explain DarkTrace X architecture."].map(q=><button key={q} onClick={()=>void send(q)}>{q}<ArrowUpRight size={14}/></button>)}</div>}
        {messages.map((m,i)=><article key={i} className={`copilot-message ${m.role}`}><div className="copilot-message-label">{m.role==="user"?"YOU":"DARKTRACE AI · GENERATED ASSESSMENT"}{m.role==="assistant"&&m.content&&<button aria-label="Copy response" onClick={()=>void navigator.clipboard.writeText(m.content)}><Copy size={13}/></button>}</div><ReactMarkdown skipHtml remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeHighlight]} components={{img:()=>null,a:({href,children})=><a href={href&&/^https?:\/\//.test(href)?href:undefined} target="_blank" rel="noopener noreferrer">{children}</a>}}>{m.content||"Gathering evidence…"}</ReactMarkdown>{m.sources?.length? <div className="copilot-sources">{m.sources.map((s,j)=><div key={j}><strong>{s.mode??"LIVE"} · {s.source}</strong>{s.reference?.startsWith("https://")&&<a href={s.reference} target="_blank" rel="noopener noreferrer">Reference ↗</a>}<small>Retrieved {s.retrieved_at?new Date(s.retrieved_at).toLocaleString():"timestamp unavailable"}</small></div>)}</div>:null}</article>)}
      </div><div className="copilot-generation"><span className={busy?"generating":""}/>{activity}</div><form className="copilot-composer" onSubmit={e=>{e.preventDefault();void send(input);}}><textarea aria-label="Message cybersecurity copilot" rows={2} maxLength={6000} value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about evidence, alerts, CVEs or DarkTrace X…" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send(input);}}}/>{busy?<button type="button" aria-label="Stop generation" onClick={()=>abort.current?.abort()}><Square size={18}/></button>:<button aria-label="Send copilot message" disabled={!input.trim()}><Send size={18}/></button>}</form><footer className="copilot-controls"><label><input type="checkbox" checked={cloud} onChange={e=>setCloud(e.target.checked)}/>Allow cloud for this request</label><button disabled={busy||messages.length<2||!sessionId} onClick={()=>void send(messages.at(-2)?.content??"",true)}><RefreshCw size={12}/>Regenerate</button><button disabled={busy} onClick={()=>void clear()}>Clear conversation</button></footer></div></div>}
      {view==="signals"&&<div className="copilot-content"><h2><Bell size={20}/> Evidence-driven alerts</h2><p>High-priority recorded events. Maximum 3 new notifications/hour and a 10-minute source cooldown.</p>{notices.filter(n=>!["dismiss","resolve","mute"].includes(n.state)).map(n=><article className="copilot-notice" key={n.id}><small className={n.severity.toLowerCase()}>{n.severity} · LIVE · {n.state}</small><h3>{n.title}</h3>{n.alert_id&&<button onClick={()=>void send("Explain this alert: observed facts, impact, confidence, investigation and response.",false,n.alert_id)}>Ask AI</button>}<button onClick={()=>void action(n,"dismiss")}>Dismiss</button><button onClick={()=>void action(n,"mute")}>Mute similar</button><button onClick={()=>void action(n,"snooze")}>Snooze 30m</button>{role!=="viewer"&&<button onClick={()=>void action(n,"resolve")}>Mark resolved</button>}</article>)}{!notices.length&&<p>No important events recorded. No synthetic alerts are generated.</p>}</div>}
      {view==="system"&&<div className="copilot-content"><h2>AI Command Center</h2><div className="copilot-status-grid">{[["AI ENGINE",status?.models.primary.provider??"UNAVAILABLE"],["LOCAL MODEL",modelState],["THREAT INTELLIGENCE",status?.sources.cisa_kev?"CONFIGURED":"UNAVAILABLE"],["DARK WEB MONITOR","UNAVAILABLE"],["SYSTEM HEALTH",status&&Object.values(status.services).every(v=>v==="ONLINE")?"ONLINE":"DEGRADED"]].map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><h3>Service health</h3>{Object.entries(status?.services??{}).map(([name,value])=><p key={name}>{name} <b>{value}</b></p>)}<p>Inference backend: {status?.local_model.backend??"Unavailable"}</p><h3>Knowledge / RAG</h3><p>{status?.knowledge.chunks??0} indexed chunks · {status?.knowledge.mode??"UNAVAILABLE"}</p><small>{status?.knowledge.sources.join(" · ")}</small>{role==="admin"&&<button onClick={()=>void request("/knowledge/reindex",{method:"POST"}).then(refresh).catch(e=>setError(String(e)))}>Refresh allowlisted knowledge</button>}<h3>Recent generation statistics</h3>{status?.usage.slice(0,5).map((u,i)=><p key={i}>{u.provider} · {(u.latency_ms/1000).toFixed(1)}s · {u.tokens??"Unavailable"} tokens</p>)}<h3>Tool invocation history</h3>{status?.tool_calls.slice(0,10).map(t=><p key={t.id}>{t.tool} · {t.mode} · {new Date(t.at).toLocaleTimeString()}</p>)}<h3>Intelligence sources</h3>{Object.entries(status?.sources??{}).map(([name,detail])=><p key={name}><strong>{name}</strong><br/>{detail}</p>)}<h3>Controlled memory</h3><label><input type="checkbox" checked={preferences.memory_enabled} onChange={e=>void saveMemory({...preferences,memory_enabled:e.target.checked})}/> Remember conversations and incident context</label><label>Response preferences<input value={preferences.preference} maxLength={500} onChange={e=>setPreferences({...preferences,preference:e.target.value})} onBlur={()=>void saveMemory(preferences)}/></label><button disabled={busy} onClick={()=>{if(window.confirm("Delete all your stored AI conversations, incident context and preferences?"))void request("/memory",{method:"DELETE"}).then(()=>{setMessages([]);setSessionId(undefined);setSessions([]);setPreferences({memory_enabled:true,preference:"",muted_groups:[]});});}}>Delete stored AI memory</button>{preferences.muted_groups.length>0&&<button onClick={()=>void saveMemory({...preferences,muted_groups:[]})}>Unmute all alert groups</button>}</div>}
      {view==="models"&&role==="admin"&&<div className="copilot-content"><h2><Settings2 size={20}/> Settings → AI</h2><p>Local Qwen is the default and never sends prompts off this machine. External AI is optional and requires explicit enablement.</p><form className="copilot-model-form" onSubmit={saveModel}><label>AI mode<select value={slot} onChange={e=>setSlot(e.target.value)}>{["primary","external"].map(s=><option key={s}>{s}</option>)}</select></label><label>Provider<select value={modelForm.provider} onChange={e=>setModelForm({...modelForm,provider:e.target.value as "local"|"external",endpoint:"",secret_env:""})}>{providers.map(p=><option key={p}>{p}</option>)}</select></label>{([['Model','model'],['API base URL','endpoint']] as const).map(([label,key])=><label key={key}>{label}<input value={modelForm[key]} onChange={e=>setModelForm({...modelForm,[key]:e.target.value})}/></label>)}{modelForm.provider==="external"&&<label>External API key<input type="password" value={modelForm.api_key??""} placeholder="Stored server-side" onChange={e=>setModelForm({...modelForm,api_key:e.target.value,enabled:true,secret_env:"EXTERNAL_AI_API_KEY"})}/></label>}<p>External configured: {modelForm.has_key?"Yes":"No"}</p><button>Save AI configuration</button>{modelForm.provider==="external"&&<button type="button" onClick={()=>void testExternal()}>Test external connection</button>}</form><p>Qwen model path, context, threads and GPU layers remain deployment settings.</p></div>}
    </section>}
  </>;
}
