"use client";
import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "../lib/api";
type Node = {id:string;type:string;label:string;risk:number};
type Edge = {source:string;target:string;relation:string};
export function IntelligenceGraph({apiBase}:{apiBase:string}) {
  const [data,setData]=useState<{nodes:Node[];edges:Edge[]}>({nodes:[],edges:[]});const [query,setQuery]=useState("");const [selected,setSelected]=useState<Node|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [revision,setRevision]=useState(0);
  useEffect(()=>{let active=true;setLoading(true);apiRequest<typeof data>(apiBase,"/intelligence/graph").then(d=>{if(active){setData(d);setError("")}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[apiBase,revision]);
  const nodes=useMemo(()=>{const matches=data.nodes.filter(n=>n.label.toLowerCase().includes(query.toLowerCase()));return matches.slice(0,60).map((n,i)=>({...n,x:500+Math.cos(2*Math.PI*i/Math.max(matches.slice(0,60).length,1))*360,y:320+Math.sin(2*Math.PI*i/Math.max(matches.slice(0,60).length,1))*250}));},[data,query]);
  const edges=data.edges.filter(e=>nodes.some(n=>n.id===e.source)&&nodes.some(n=>n.id===e.target));
  return <div className="advanced-workspace"><section className="module-header"><p>EVIDENCE RELATIONSHIPS</p><h1>Intelligence graph</h1><span>Explore recorded IOC tags and source-attributed actor techniques.</span></section><div className="module-form"><input aria-label="Filter graph nodes" placeholder="Filter node labels…" value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={loading} onClick={()=>setRevision(r=>r+1)}>Refresh graph</button></div>{error&&<div className="module-notice error">{error}</div>}<article className="module-card"><p>{data.nodes.length} recorded nodes · {data.edges.length} relationships · showing up to 60 matching nodes</p>{loading?<div className="module-loading">Loading graph…</div>:nodes.length?<svg viewBox="0 0 1000 640" role="img" aria-label="Interactive intelligence graph" style={{width:"100%",minHeight:300}}>{edges.map((e,i)=>{const a=nodes.find(n=>n.id===e.source)!;const b=nodes.find(n=>n.id===e.target)!;return <line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="#56b8c6" strokeOpacity={.35}><title>{e.relation}</title></line>})}{nodes.map(n=><g key={n.id} tabIndex={0} role="button" aria-label={`${n.type}: ${n.label}`} onClick={()=>setSelected(n)} onKeyDown={e=>{if(e.key==="Enter")setSelected(n)}} style={{cursor:"pointer"}}><circle cx={n.x} cy={n.y} r={selected?.id===n.id?15:10} fill={n.type==="actor"?"#a78bfa":n.type==="ioc"?"#22d3ee":"#4ade80"}/><text x={n.x} y={n.y-20} textAnchor="middle" fill="currentColor" fontSize={11}>{n.label.length>26?n.label.slice(0,23)+"…":n.label}</text><title>{n.label}</title></g>)}</svg>:<div className="empty-state">No matching nodes. Add sourced indicators or actor profiles to build your graph.</div>}</article>{selected&&<article className="module-card"><h2>{selected.label}</h2><p>{selected.type} · recorded risk {selected.risk}/100</p>{data.edges.filter(e=>e.source===selected.id||e.target===selected.id).map((e,i)=><p key={i}>{e.relation.replaceAll("_"," ")} → {data.nodes.find(n=>n.id===(e.source===selected.id?e.target:e.source))?.label}</p>)}</article>}</div>;
}
