"use client";
import { FormEvent, useEffect, useState } from "react";
import { apiRequest } from "../lib/api";
import { askCopilot } from "./copilot";
type Row = Record<string, unknown>;
export type OperationsFeature = "administration" | "intelligence" | "alerts" | "assets" | "exposure";
const definitions = {
  administration: {title:"Workspace administration", description:"Manage users, roles, service health and audit history.", endpoint:"/tenants/users"},
  intelligence: {title:"IOC intelligence", description:"Record sourced indicators, correlate exact observables, and search your tenant intelligence.", endpoint:"/iocs"},
  alerts: {title:"Alert center", description:"Triage recorded evidence and track each alert through resolution.", endpoint:"/operational-alerts"},
  assets: {title:"Asset inventory", description:"Register owned assets and track their exposure and responsible teams.", endpoint:"/assets"},
  exposure: {title:"Keyword monitoring", description:"Match brand and infrastructure terms against actual public or licensed source records.", endpoint:"/monitors/keywords"}
};
export function OperationsWorkspace({feature,apiBase}:{feature:OperationsFeature;apiBase:string}) {
  const def=definitions[feature];const [rows,setRows]=useState<Row[]>([]);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [revision,setRevision]=useState(0);const [form,setForm]=useState<Record<string,string>>({});const [query,setQuery]=useState("");const [result,setResult]=useState<unknown>(null);const [status,setStatus]=useState<Row>({});const [audit,setAudit]=useState<Row[]>([]);const [mentions,setMentions]=useState<Row[]>([]);const [role,setRole]=useState("viewer");
  const value=(key:string)=>form[key]??"";const change=(key:string,v:string)=>setForm(f=>({...f,[key]:v}));
  useEffect(()=>{let active=true;setLoading(true);setError("");async function load(){try{const [data,me]=await Promise.all([apiRequest<Row[]>(apiBase,def.endpoint),apiRequest<{role:string}>(apiBase,"/auth/me")]);if(active){setRows(data);setRole(me.role);}if(feature==="administration"){const [s,a]=await Promise.all([apiRequest<Row>(apiBase,"/platform/status"),apiRequest<Row[]>(apiBase,"/audit/events/operational")]);if(active){setStatus(s);setAudit(a);}}if(feature==="exposure"){const m=await apiRequest<Row[]>(apiBase,"/exposure/mentions");if(active)setMentions(m);}}catch(e){if(active)setError(e instanceof Error?e.message:"Unable to load workspace");}finally{if(active)setLoading(false);}}void load();return()=>{active=false}},[feature,apiBase,def.endpoint,revision]);
  async function run(work:()=>Promise<void>){setBusy(true);setError("");setNotice("");try{await work()}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}}
  const write=async(path:string,body:unknown,method="POST")=>apiRequest(apiBase,path,{method,body:JSON.stringify(body)});
  async function create(event:FormEvent){event.preventDefault();void run(async()=>{let body:unknown;
    if(feature==="administration")body={email:value("email"),display_name:value("name"),password:value("password"),role:value("role")||"viewer"};
    else if(feature==="intelligence")body={type:value("type")||"domain",value:value("value"),source:value("source"),risk_score:Number(value("risk")),confidence:Number(value("confidence")||50),tags:value("tags").split(",").map(t=>t.trim()).filter(Boolean)};
    else if(feature==="assets")body={hostname:value("hostname"),owner:value("owner"),exposure:value("exposure")||"internal",criticality:value("criticality")||"medium",risk_score:Number(value("risk")),services:value("services").split(",").map(t=>t.trim()).filter(Boolean)};
    else body={term:value("term"),categories:[]};
    await write(def.endpoint,body);setForm({});setNotice("Saved to your workspace.");setRevision(r=>r+1);
  })}
  const input=(label:string,key:string,type="text",required=true)=><label key={key}>{label}<input type={type} required={required} value={value(key)} min={type==="number"?0:undefined} max={type==="number"?100:undefined} onChange={e=>change(key,e.target.value)}/></label>;
  const select=(label:string,key:string,choices:string[])=><label key={key}>{label}<select value={value(key)||choices[0]} onChange={e=>change(key,e.target.value)}>{choices.map(c=><option key={c}>{c}</option>)}</select></label>;
  const canWrite=role!=="viewer";
  return <div className="advanced-workspace"><section className="module-header"><p>LIVE WORKSPACE</p><h1>{def.title}</h1><span>{def.description}</span><button className="advanced-refresh" disabled={busy||loading} onClick={()=>setRevision(r=>r+1)}>Refresh</button></section>{error&&<div className="module-notice error" role="alert">{error}</div>}{notice&&<div className="module-notice success" role="status">{notice}</div>}
    {feature==="administration"&&<div className="advanced-stats">{Object.entries(status).map(([key,v])=><article className="module-card" key={key}><span>{key.replaceAll("_"," ")}</span><b>{String(v)}</b></article>)}</div>}
    {feature!=="alerts"&&canWrite&&<article className="module-card"><h2>{feature==="administration"?"Invite a workspace user":feature==="intelligence"?"Add sourced indicator":feature==="assets"?"Register asset":"Add monitored keyword"}</h2><form className="stacked-form" onSubmit={create}><div className="form-split">{feature==="administration"?<>{input("Name","name")}{input("Email","email","email")}{input("Initial password (12+ characters)","password","password")}{select("Role","role",["viewer","analyst","lead","admin"])}</>:feature==="intelligence"?<>{select("Indicator type","type",["domain","ip","url","hash","email"])}{input("Indicator","value")}{input("Source / evidence reference","source")}{input("Source risk score (0–100)","risk","number")}{input("Confidence (0–100)","confidence","number")}{input("Tags, comma separated","tags","text",false)}</>:feature==="assets"?<>{input("Hostname","hostname")}{input("Owner","owner")}{select("Exposure","exposure",["internal","internet"])}{select("Criticality","criticality",["medium","low","high","critical"])}{input("Assessed risk score","risk","number")}{input("Services, comma separated","services","text",false)}</>:input("Brand, domain, product or keyword","term")}</div><button disabled={busy}>{busy?"Saving…":"Save"}</button></form></article>}
    {feature==="intelligence"&&<article className="module-card"><h2>Exact IOC correlation</h2><form className="module-form" onSubmit={e=>{e.preventDefault();void run(async()=>setResult(await apiRequest(apiBase,`/intelligence/iocs/correlate?indicator_type=${encodeURIComponent(value("lookupType")||"domain")}&value=${encodeURIComponent(value("lookup"))}`)))}}>{select("Type","lookupType",["domain","ip","url","hash","email"])}{input("Observable","lookup")}<button disabled={busy}>Correlate in Elasticsearch</button></form>{role==="admin"&&<button disabled={busy} onClick={()=>void run(async()=>{setResult(await write("/intelligence/reindex",{}));setNotice("Search index synchronized.")})}>Sync search index</button>}</article>}
    {feature==="exposure"&&<article className="module-card"><h2>Source ingestion</h2><p>CISA KEV provides public vulnerability intelligence. Dark-web coverage requires actual records from a licensed provider; no provider is currently assumed.</p><div className="advanced-actions"><button disabled={busy||!canWrite} onClick={()=>void run(async()=>{setResult(await write("/threat-feeds/cisa-kev/ingest",{}));setRevision(r=>r+1)})}>Ingest CISA KEV</button></div><details><summary>Import public or licensed intelligence records</summary><form className="stacked-form" onSubmit={e=>{e.preventDefault();void run(async()=>{setResult(await write("/exposure/ingest",JSON.parse(value("sourceJson"))));setRevision(r=>r+1)})}}><label>Source JSON<textarea required rows={8} value={value("sourceJson")} onChange={e=>change("sourceJson",e.target.value)} placeholder={'{"source":"provider-name","source_type":"licensed_dark_web","legal_basis":"Licensed subscription","items":[{"external_id":"record-id","title":"Source title","summary":"Source text","source_url":"https://provider.example/record","observed_at":"2026-09-14T10:00:00Z"}]}'}/></label><button disabled={busy||!canWrite}>Import and match keywords</button></form></details></article>}
    <article className="module-card"><div className="module-form"><input aria-label="Search records" placeholder="Filter records…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{loading?<div className="module-loading">Loading records…</div>:<div className="advanced-results">{rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map(row=><article className="advanced-tool" key={String(row.id)}><h2>{String(row.title??row.value??row.hostname??row.term??row.display_name??row.id)}</h2><p>{String(row.source??row.email??row.owner??"")}</p>{row.severity!=null&&<span className={`status-pill ${row.severity}`}>{String(row.severity)} · {String(row.score)}/100</span>}{feature==="alerts"&&<button onClick={()=>askCopilot(String(row.id))}>Ask AI</button>}{feature==="alerts"&&<label>Status<select disabled={busy||!canWrite} value={String(row.status)} onChange={e=>void run(async()=>{await write(`/operational-alerts/${row.id}`,{status:e.target.value},"PATCH");setRevision(r=>r+1)})}>{["open","triage","investigating","resolved","false_positive"].map(s=><option key={s}>{s}</option>)}</select></label>}{feature==="administration"&&<label>Role<select disabled={busy} value={String(row.role)} onChange={e=>void run(async()=>{await write(`/tenants/users/${row.id}/role`,{role:e.target.value},"PATCH");setRevision(r=>r+1)})}>{["viewer","analyst","lead","admin"].map(r=><option key={r}>{r}</option>)}</select></label>}{feature==="exposure"&&<button disabled={busy||!canWrite} onClick={()=>void run(async()=>{await apiRequest(apiBase,`/monitors/keywords/${row.id}`,{method:"DELETE"});setRevision(r=>r+1)})}>Remove monitor</button>}<details><summary>Evidence and details</summary><pre className="advanced-output">{JSON.stringify(row,null,2)}</pre></details></article>)}{rows.length===0&&<div className="empty-state">No records yet. New evidence will appear here when added.</div>}</div>}</article>
    {feature==="exposure"&&<article className="module-card"><h2>Matched source evidence</h2>{mentions.length?mentions.map((m,i)=><details key={i}><summary>{String(m.monitored_term)} · {String(m.source_type)}</summary><pre className="advanced-output">{JSON.stringify(m,null,2)}</pre></details>):<div className="empty-state">No source matches yet.</div>}</article>}
    {feature==="administration"&&<article className="module-card"><h2>Audit history</h2>{audit.map(a=><div className="data-row" key={String(a.id)}><strong>{String(a.action)}</strong><span>{String(a.actor_id)}</span><time>{new Date(String(a.occurred_at)).toLocaleString()}</time></div>)}</article>}
    {result!==null&&<article className="module-card"><h2>Result</h2><pre className="advanced-output">{JSON.stringify(result,null,2)}</pre></article>}
  </div>;
}
